In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import recall_score, accuracy_score, classification_report, f1_score
from xgboost import XGBClassifier
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv(r"D:\Data Analytics & Data Science\NetMax Technologies\DataSet From claude\diabetic_readmission_dataset.csv")
df.head(20)

,patient_id,age,gender,race,admission_type,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses,primary_diagnosis,max_glu_serum,A1Cresult,insulin,change,diabetesMed,readmitted
0,100000,[50-60),Female,Caucasian,Urgent,2,25.0,1,15,0,1,0,7,Diabetes,NaN,Norm,No,Ch,No,0
1,100001,[80-90),Female,Caucasian,Emergency,9,59.0,1,27,0,1,0,9,Other,NaN,>7,No,Ch,Yes,1
2,100002,[70-80),Male,Caucasian,Emergency,2,8.0,1,25,0,0,1,9,Diabetes,NaN,Norm,Steady,Ch,No,0
3,100003,[60-70),Female,Caucasian,Elective,7,47.0,1,12,2,0,0,7,Digestive,NaN,>8,No,Ch,Yes,0
4,100004,[40-50),Female,Other,Elective,3,29.0,2,27,0,0,0,8,Injury,NaN,NaN,Steady,No,No,0
5,100005,[40-50),Male,Caucasian,Emergency,4,73.0,0,16,0,0,1,4,Injury,NaN,Norm,No,Ch,Yes,0
6,100006,[20-30),Female,Caucasian,Urgent,8,12.0,4,17,0,0,1,11,Respiratory,NaN,NaN,Up,Ch,Yes,0
7,100007,[80-90),Male,Caucasian,Emergency,5,38.0,2,15,0,1,1,8,Circulatory,NaN,>8,No,No,No,0
8,100008,[60-70),Female,Caucasian,Emergency,4,27.0,0,22,0,0,0,7,Other,NaN,>8,No,No,Yes,0
9,100009,[70-80),Male,Caucasian,Emergency,10,32.0,2,9,1,1,0,5,Injury,NaN,>8,Up,No,No,1


In [6]:
df.isnull().sum()

patient_id            0
age                   0
gender                0
race                  0
admission_type        0
time_in_hospital      0
num_lab_procedures    0
num_procedures        0
num_medications       0
number_outpatient     0
number_emergency      0
number_inpatient      0
number_diagnoses      0
primary_diagnosis     0
max_glu_serum         0
A1Cresult             0
insulin               0
change                0
diabetesMed           0
readmitted            0
dtype: int64

In [5]:
# handling missing values

df["num_lab_procedures"] = df["num_lab_procedures"].fillna(df["num_lab_procedures"].median())

df["max_glu_serum"] =df["max_glu_serum"].fillna(df["max_glu_serum"].mode()[0])

df["A1Cresult"] = df["A1Cresult"].fillna(df["A1Cresult"].mode()[0])


In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.head()

,patient_id,age,gender,race,admission_type,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses,primary_diagnosis,max_glu_serum,A1Cresult,insulin,change,diabetesMed,readmitted
0,100000,[50-60),Female,Caucasian,Urgent,2,25.0,1,15,0,1,0,7,Diabetes,Norm,Norm,No,Ch,No,0
1,100001,[80-90),Female,Caucasian,Emergency,9,59.0,1,27,0,1,0,9,Other,Norm,>7,No,Ch,Yes,1
2,100002,[70-80),Male,Caucasian,Emergency,2,8.0,1,25,0,0,1,9,Diabetes,Norm,Norm,Steady,Ch,No,0
3,100003,[60-70),Female,Caucasian,Elective,7,47.0,1,12,2,0,0,7,Digestive,Norm,>8,No,Ch,Yes,0
4,100004,[40-50),Female,Other,Elective,3,29.0,2,27,0,0,0,8,Injury,Norm,>8,Steady,No,No,0


In [10]:
df["A1Cresult"].value_counts()

A1Cresult
>8      5935
>7      1245
Norm     820
Name: count, dtype: int64

In [14]:
# hanlding categorical data

label = LabelEncoder()

column = ["age","gender","race","admission_type", "primary_diagnosis","max_glu_serum","A1Cresult","insulin","change","diabetesMed"]
for item in column:
    df[item] = label.fit_transform(df[item])


In [15]:
df.head()

,patient_id,age,gender,race,admission_type,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses,primary_diagnosis,max_glu_serum,A1Cresult,insulin,change,diabetesMed,readmitted
0,100000,5,0,2,2,2,25.0,1,15,0,1,0,7,1,2,2,1,0,0,0
1,100001,8,0,2,1,9,59.0,1,27,0,1,0,9,5,2,0,1,0,1,1
2,100002,7,1,2,1,2,8.0,1,25,0,0,1,9,1,2,2,2,0,0,0
3,100003,6,0,2,0,7,47.0,1,12,2,0,0,7,2,2,1,1,0,1,0
4,100004,4,0,4,0,3,29.0,2,27,0,0,0,8,3,2,1,2,1,0,0


In [16]:
df.drop("patient_id", axis=1, inplace=True)

In [17]:
df.head()

,age,gender,race,admission_type,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses,primary_diagnosis,max_glu_serum,A1Cresult,insulin,change,diabetesMed,readmitted
0,5,0,2,2,2,25.0,1,15,0,1,0,7,1,2,2,1,0,0,0
1,8,0,2,1,9,59.0,1,27,0,1,0,9,5,2,0,1,0,1,1
2,7,1,2,1,2,8.0,1,25,0,0,1,9,1,2,2,2,0,0,0
3,6,0,2,0,7,47.0,1,12,2,0,0,7,2,2,1,1,0,1,0
4,4,0,4,0,3,29.0,2,27,0,0,0,8,3,2,1,2,1,0,0


In [18]:
# feature selection
x = df.drop(columns=["readmitted"])
y = df["readmitted"]

In [19]:
from sklearn.model_selection import train_test_split


x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [22]:
# using logistics regression

model_logistic_regressor = LogisticRegression(max_iter=100)

model_logistic_regressor.fit(x_train,y_train)

d:\Data Analytics & Data Science\General Practice\General ML practise\rana\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [28]:
y_pred_lr = model_logistic_regressor.predict(x_test)
acc_lr= accuracy_score(y_test,y_pred_lr)
print(f"Accuracy score with Logistic Regression: {acc_lr:.2f}")

Accuracy score with Logistic Regression: 0.86


In [25]:
from sklearn.metrics import confusion_matrix


confusion_matrix(y_test,y_pred_lr)

array([[1355,   12],
       [ 214,   19]])

In [27]:
# scaling the data to improve the accuracy 

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [30]:
model_logistic_regressor.fit(x_train_scaled,y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [33]:
y_pred_scaled_lr = model_logistic_regressor.predict(x_test_scaled)
acc_scaled_lr = accuracy_score(y_test,y_pred_scaled_lr)
print(f"Accuracy score with scaled data (Logistic Regression) : {acc_scaled_lr:.2f}")

Accuracy score with scaled data (Logistic Regression) : 0.86


In [34]:
confusion_matrix(y_test,y_pred_scaled_lr)

array([[1351,   16],
       [ 210,   23]])

In [35]:
# using xgboost ang grid search

import random

from sklearn.model_selection import GridSearchCV


best_para = {"max_depth" :[3,5,7,12],
             "n_estimators" : [200,250,300,350]}

model = RandomForestClassifier(random_state=42)

grid_search=GridSearchCV(estimator=model,
                         param_grid=best_para,
                         cv=5,
                         n_jobs=-1,
                         verbose=1)

grid_search.fit(x_train_scaled,y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits


,estimator,RandomForestC...ndom_state=42)
,param_grid,"{'max_depth': [3, 5, ...], 'n_estimators': [200, 250, ...]}"
,scoring,None
,n_jobs,-1
,refit,True
,cv,5
,verbose,1
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,n_estimators,300


In [36]:
best_model = grid_search.best_estimator_

In [37]:
y_pred_xg = best_model.predict(x_test_scaled)
acc_xg = accuracy_score(y_test,y_pred_xg)
print(f"Accuracy score with XGBOOST: {acc_xg:.2f}")

Accuracy score with XGBOOST: 0.86


In [38]:
confusion_matrix(y_test,y_pred_xg)

array([[1366,    1],
       [ 229,    4]])

In [40]:
classification_report(y_test,y_pred_xg)

'              precision    recall  f1-score   support\n\n           0       0.86      1.00      0.92      1367\n           1       0.80      0.02      0.03       233\n\n    accuracy                           0.86      1600\n   macro avg       0.83      0.51      0.48      1600\nweighted avg       0.85      0.86      0.79      1600\n'